import type { Metadata } from 'next'
import '@/public/fonts/yekan-bakh/fontiran.css'
import '@/app/globals.css'
import HomeSVG from '@/icons/home.svg'
import HomeFilledSVG from '@/icons/home-filled.svg'
import GridViewSVG from '@/icons/grid-view.svg'
import SearchSVG from '@/icons/search.svg'
import ShoppingBagSVG from '@/icons/shopping-bag.svg'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-[calc(100dvh-4rem)]">
          {children}
        </main>

        <footer className="bg-white border-t sticky bottom-0 z-40">
          <nav className="flex gap-0 text-center">
            <a className="flex flex-col px-0 py-2 flex-grow pr-2 text-purple-500">
              <HomeFilledSVG className="fill-current h-6 w-6 mx-auto" />
              <span className="leading-4 text-xs opacity-70">خانه</span>
            </a>
            <a className="flex flex-col px-0 py-2 flex-grow">
              <GridViewSVG className="fill-current h-6 w-6 mx-auto" />
              <span className="leading-4 text-xs opacity-70">دسته‌بندی</span>
            </a>
            <a className="flex flex-col px-0 py-2 flex-grow">
              <SearchSVG className="fill-current h-6 w-6 mx-auto" />
              <span className="leading-4 text-xs opacity-70">جستجو</span>
            </a>
            <a className="flex flex-col px-0 py-2 flex-grow pl-2">
              <ShoppingBagSVG className="fill-current h-6 w-6 mx-auto" />
              <span className="leading-4 text-xs opacity-70">سبد خرید</span>
            </a>
          </nav>
        </footer>
      </body>
    </html>
  )
}
