import type { Metadata } from 'next'
import '@/public/fonts/yekan-bakh/fontiran.css'
import '@/app/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-gray-200 h-16 sticky top-0">

        </header>

        <main className="min-h-[calc(100dvh-8rem)]">
          {children}
        </main>

        <footer className="bg-white border-t sticky bottom-0">
          <nav className="grid grid-cols-5 gap-2 text-center">
            <a className="px-0 py-4">
              <span className="bg-gray-400 h-8 w-8 block rounded-full mx-auto">&nbsp;</span>
            </a>
            <a className="px-0 py-4">
              <span className="bg-gray-400 h-8 w-8 block rounded-full mx-auto">&nbsp;</span>
            </a>
            <a className="px-0 py-4">
              <span className="bg-gray-400 h-8 w-8 block rounded-full mx-auto">&nbsp;</span>
            </a>
            <a className="px-0 py-4">
              <span className="bg-gray-400 h-8 w-8 block rounded-full mx-auto">&nbsp;</span>
            </a>
            <a className="px-0 py-4">
              <span className="bg-gray-400 h-8 w-8 block rounded-full mx-auto">&nbsp;</span>
            </a>
          </nav>
        </footer>
      </body>
    </html>
  )
}
