import type { Metadata } from 'next'
import '@/public/fonts/yekan-bakh/fontiran.css'
import '@/app/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen">
          {children}
        </main>

        <footer className="bg-gray-100 sticky bottom-0">
          <nav className="grid grid-cols-5 gap-2 text-center">
          <a className="p-4">
              <span className="bg-gray-400 h-6 w-6 block rounded-full mx-auto">&nbsp;</span>
            </a>
            <a className="p-4">
              <span className="bg-gray-400 h-6 w-6 block rounded-full mx-auto">&nbsp;</span>
            </a>
            <a className="p-4">
              <span className="bg-gray-400 h-6 w-6 block rounded-full mx-auto">&nbsp;</span>
            </a>
            <a className="p-4">
              <span className="bg-gray-400 h-6 w-6 block rounded-full mx-auto">&nbsp;</span>
            </a>
            <a className="p-4">
              <span className="bg-gray-400 h-6 w-6 block rounded-full mx-auto">&nbsp;</span>
            </a>
          </nav>
        </footer>
      </body>
    </html>
  )
}
